[versions]
kotlin = "1.9.25"
ktlint = "12.2.0"
junit = "5.10.0"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit = { module = "org.junit.jupiter:junit-jupiter" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
